### ISSUE TITLE
v0.5.6 dev-url docker timeout

### ISSUE THREAD

**Issue by fasibio** [ariga/terraform-provider-atlas#96]
I get a timeout with current version 
with 0.5.4 it works like it should

**Comment by feigi** [comment]
Hey Fasibio, 

can you post the exact error? Does it happen on your machine as well? I'm asking because I'm facing a weird timeout issue as well, but only on CICD and I also have green runs with the same version, so currently I suspect the CICD runner not the Atlas Terraform provider. Nevertheless I wanted to compare notes.

```shell
module.db_migration.data.atlas_migration.this: Read complete after 0s [id=file:///github/workspace/migration/infrastructure/../scripts/migrations?format=atlas]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: timeout: <nil>
│ 
│ 
│   with module.db_migration.atlas_migration.this,
│   on .terraform/modules/db_migration/modules/db-migration/migrations.tf line 12, in resource "atlas_migration" "this":
│   12: resource "atlas_migration" "this" {
│ 
╵
```

Cheers!

**Comment by giautm** [comment]
Hello @fasibio, please share a detail error here. I'll checking ASAP.

**Comment by giautm** [comment]
Hello, I'll close this issue. Please fire a new one if you still facing with it. Thank you.
